name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './epub-reader/package-lock.json'

    - name: Install dependencies
      run: |
        cd epub-reader
        npm ci --legacy-peer-deps

    - name: Build for production
      run: |
        cd epub-reader
        npm run build
      env:
        CI: false
        REACT_APP_API_BASE_URL: ${{ secrets.BACKEND_URL || 'https://your-backend-url.com/api' }}
        REACT_APP_ENVIRONMENT: production

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './epub-reader/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
        force_orphan: true
