name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd epub-reader
        npm install --legacy-peer-deps

    - name: Build for production
      run: |
        cd epub-reader
        # Set production environment variables
        export REACT_APP_API_BASE_URL=${{ secrets.BACKEND_URL || 'https://your-backend-url.com/api' }}
        export REACT_APP_ENVIRONMENT=production
        npm run build
        # Check if build directory exists
        ls -la build/
      env:
        CI: false # Treat warnings as warnings, not errors

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./epub-reader/build
        force_orphan: true
